import { useEffect, useMemo, useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { shouldPreferLocalProgress } from "@/lib/progressSync";
import { createQuestionOrder, isValidQuestionOrder, resolveQuestionOrder } from "@/lib/questionOrder";
import { BarChart3, BookOpenCheck, Brain, CheckCircle2, ChevronLeft, ChevronRight, CircleHelp, Clock3, FileText, Flag, Gauge, LayoutDashboard, ListChecks, Loader2, LogIn, LogOut, RotateCcw, Settings2, Sparkles, Target, XCircle } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Separator } from "@/components/ui/separator";
import { toast } from "sonner";

type Axis = "Gestão pública" | "Pessoas e redes" | "Políticas públicas" | "Auditoria e legislação";
type Question = { id:number; axis:Axis; topic:string; difficulty:"Fácil"|"Média"|"Difícil"; prompt:string; options:string[]; correct:number; explanation:string; source:string };
type Answer = { selected:number; correct:boolean; axis:Axis; topic:string; difficulty:Question["difficulty"] };

const axisMeta: Record<Axis,{short:string;color:string}> = {
  "Gestão pública": { short:"Gestão", color:"#2A6680" },
  "Pessoas e redes": { short:"Pessoas", color:"#54B99A" },
  "Políticas públicas": { short:"Políticas", color:"#D69A52" },
  "Auditoria e legislação": { short:"Auditoria", color:"#D56B62" },
};

const blueprints: Array<{axis:Axis;topic:string;difficulty:Question["difficulty"];prompt:string;options:string[];correct:number;explanation:string;source:string}> = [
 {axis:"Gestão pública",topic:"Planejamento estratégico",difficulty:"Média",prompt:"Em um planejamento estratégico público, a função dos indicadores é principalmente:",options:["Substituir objetivos por opiniões da equipe","Acompanhar resultados e apoiar decisões de ajuste","Registrar apenas despesas executadas","Eliminar a necessidade de avaliação"],correct:1,explanation:"Indicadores tornam objetivos observáveis e apoiam monitoramento, avaliação e correção de rota.",source:"Gestão do SUS — Ministério da Saúde"},
 {axis:"Gestão pública",topic:"Balanced Scorecard",difficulty:"Difícil",prompt:"No Balanced Scorecard, uma organização que conecta aprendizagem, processos, usuários e resultados está trabalhando com:",options:["Perspectivas articuladas por relações de causa e efeito","Uma lista de tarefas sem metas","Um modelo exclusivo de contabilidade","Um instrumento que dispensa indicadores"],correct:0,explanation:"O BSC articula perspectivas e objetivos, permitindo acompanhar relações de causa e efeito e a execução da estratégia.",source:"Conteúdo programático do edital; materiais institucionais de gestão"},
 {axis:"Gestão pública",topic:"Gestão por resultados",difficulty:"Média",prompt:"A gestão por resultados se diferencia de uma gestão centrada apenas em procedimentos porque enfatiza:",options:["O cumprimento formal sem medir entregas","Resultados, indicadores, metas e responsabilização","A eliminação de controles","A autonomia sem prestação de contas"],correct:1,explanation:"Gestão por resultados combina objetivos, indicadores, metas, monitoramento e responsabilização.",source:"Glossário de monitoramento e avaliação — Ministério da Saúde"},
 {axis:"Gestão pública",topic:"Cultura organizacional",difficulty:"Média",prompt:"Em processos de mudança no setor público, a cultura organizacional deve ser compreendida como:",options:["Conjunto de valores, crenças e práticas compartilhadas","Regulamento publicado no diário oficial","Organograma da instituição","Somente o comportamento do dirigente"],correct:0,explanation:"Cultura envolve padrões compartilhados que influenciam interpretações, decisões e práticas de trabalho.",source:"Conteúdo programático do edital"},
 {axis:"Gestão pública",topic:"Transparência",difficulty:"Fácil",prompt:"A transparência pública contribui diretamente para:",options:["Reduzir o controle social","Ampliar acesso à informação e accountability","Impedir participação cidadã","Substituir todos os controles internos"],correct:1,explanation:"Transparência amplia o acesso a informações e cria condições para controle social e responsabilização.",source:"Portal da Transparência; Governo Digital"},
 {axis:"Gestão pública",topic:"Governo eletrônico",difficulty:"Fácil",prompt:"Uma iniciativa de governo eletrônico orientada ao cidadão deve priorizar:",options:["Apenas digitalizar formulários existentes","Acessibilidade, integração e facilidade de acesso a serviços","Restringir canais presenciais sem alternativa","Manter dados isolados entre órgãos"],correct:1,explanation:"Governo digital deve melhorar acesso, integração, transparência e experiência do cidadão.",source:"Estratégia Nacional de Governo Digital"},
 {axis:"Gestão pública",topic:"Controle social",difficulty:"Média",prompt:"No contexto das políticas públicas, controle social significa:",options:["Controle exclusivo pelo Poder Judiciário","Participação da sociedade no acompanhamento da ação pública","Fiscalização somente por auditor interno","Gestão sem participação de usuários"],correct:1,explanation:"Controle social envolve participação e acompanhamento da sociedade sobre políticas e serviços públicos.",source:"Portal da Transparência; Lei nº 8.142/1990"},
 {axis:"Gestão pública",topic:"Qualidade",difficulty:"Média",prompt:"Uma política de qualidade em serviços públicos deve combinar:",options:["Padronização cega e ausência de escuta","Foco no usuário, melhoria contínua e medição","Somente redução de custos","Metas sem análise de resultados"],correct:1,explanation:"Qualidade pública combina foco no cidadão, padrões, melhoria contínua e avaliação de resultados.",source:"Conteúdo programático do edital"},
 {axis:"Gestão pública",topic:"Parcerias",difficulty:"Difícil",prompt:"Processos participativos de gestão pública são mais consistentes quando:",options:["A decisão já está tomada e a consulta é simbólica","Há regras claras, informação e devolutiva aos participantes","Somente especialistas podem opinar","A participação ocorre sem transparência"],correct:1,explanation:"Participação qualificada depende de informação, regras, inclusão e retorno sobre como as contribuições foram consideradas.",source:"Governo Digital; conteúdo programático do edital"},
 {axis:"Gestão pública",topic:"Excelência",difficulty:"Fácil",prompt:"A excelência nos serviços públicos deve ser avaliada considerando:",options:["Apenas o volume de documentos produzidos","Valor entregue ao cidadão, qualidade e resultados","Somente a hierarquia formal","A ausência de reclamações registradas"],correct:1,explanation:"Excelência se relaciona ao valor público entregue, à qualidade percebida e aos resultados obtidos.",source:"Conteúdo programático do edital"},
 {axis:"Pessoas e redes",topic:"Competências",difficulty:"Fácil",prompt:"Em gestão de pessoas, competência é melhor compreendida como:",options:["Somente conhecimento teórico","Mobilização de conhecimentos, habilidades e atitudes em contexto","Tempo de serviço","Cargo ocupado no organograma"],correct:1,explanation:"Competência envolve mobilizar conhecimentos, habilidades e atitudes para produzir entregas em determinado contexto.",source:"Gestão por competências — ENAP"},
 {axis:"Pessoas e redes",topic:"Gestão por competências",difficulty:"Média",prompt:"O modelo integrado de gestão por competências procura alinhar:",options:["Competências individuais, estratégia e entregas organizacionais","Folha de pagamento e férias apenas","Punições e controle disciplinar","Treinamento sem diagnóstico"],correct:0,explanation:"O modelo integrado conecta estratégia, competências necessárias, desenvolvimento e resultados organizacionais.",source:"Gestão por competências — ENAP"},
 {axis:"Pessoas e redes",topic:"Espaço ocupacional",difficulty:"Difícil",prompt:"O conceito de espaço ocupacional está relacionado:",options:["À amplitude de atuação e responsabilidade assumida pelo indivíduo","Ao tamanho físico do setor","À quantidade de servidores do órgão","Ao endereço funcional"],correct:0,explanation:"Espaço ocupacional expressa a ampliação da atuação e das responsabilidades em contextos de maior complexidade.",source:"Gestão por competências — ENAP"},
 {axis:"Pessoas e redes",topic:"Competência organizacional",difficulty:"Média",prompt:"A competência como elo entre indivíduo e organização ocorre quando:",options:["A capacidade individual gera entrega coerente com a estratégia","A organização ignora resultados","O indivíduo atua sem contexto","Competências são apenas atributos pessoais"],correct:0,explanation:"O elo aparece quando conhecimentos e capacidades individuais se convertem em entregas alinhadas à organização.",source:"Gestão por competências — ENAP"},
 {axis:"Pessoas e redes",topic:"Gestão pública de pessoas",difficulty:"Média",prompt:"Um limite importante da gestão por competências no setor público é:",options:["A existência de regras legais e restrições institucionais","A impossibilidade de desenvolver pessoas","A ausência completa de objetivos","A inexistência de serviços ao cidadão"],correct:0,explanation:"No setor público, a gestão deve respeitar legalidade, estruturas de carreira, orçamento e regras institucionais.",source:"Gestão por competências — ENAP"},
 {axis:"Pessoas e redes",topic:"Comunicação",difficulty:"Fácil",prompt:"Na gestão pública, comunicação efetiva requer:",options:["Mensagem única para todos os públicos","Clareza, adequação ao público e possibilidade de retorno","Somente divulgação unilateral","Informação sem contexto"],correct:1,explanation:"Comunicação pública precisa ser clara, acessível, adequada ao público e aberta ao diálogo.",source:"Conteúdo programático do edital"},
 {axis:"Pessoas e redes",topic:"Redes organizacionais",difficulty:"Difícil",prompt:"A gestão de redes organizacionais exige principalmente:",options:["Coordenação entre atores interdependentes","Comando único em todas as situações","Eliminação de negociações","Ausência de objetivos comuns"],correct:0,explanation:"Redes envolvem atores interdependentes e exigem coordenação, confiança, comunicação e objetivos compartilhados.",source:"Conteúdo programático do edital"},
 {axis:"Pessoas e redes",topic:"Liderança",difficulty:"Média",prompt:"Uma liderança orientada a resultados no setor público deve:",options:["Combinar direção, desenvolvimento da equipe e prestação de contas","Concentrar todas as decisões","Evitar indicadores","Priorizar visibilidade pessoal"],correct:0,explanation:"Liderança pública responsável articula direção, desenvolvimento, colaboração e accountability.",source:"Conteúdo programático do edital"},
 {axis:"Pessoas e redes",topic:"Desempenho",difficulty:"Média",prompt:"A avaliação de desempenho é mais útil quando:",options:["Serve apenas para punir","Está ligada a objetivos, feedback e desenvolvimento","É feita sem critérios","Ocorre somente no fim da carreira"],correct:1,explanation:"Avaliação deve produzir feedback e orientar desenvolvimento, alinhamento e melhoria das entregas.",source:"Gestão por competências — ENAP"},
 {axis:"Pessoas e redes",topic:"Mudança",difficulty:"Fácil",prompt:"A resistência a mudanças organizacionais pode ser reduzida por:",options:["Informação, participação e apoio à transição","Silêncio institucional","Metas ocultas","Punição imediata"],correct:0,explanation:"Informação, participação e suporte reduzem incerteza e ajudam a construir adesão à mudança.",source:"Conteúdo programático do edital"},
 {axis:"Pessoas e redes",topic:"Complexidade",difficulty:"Difícil",prompt:"Na gestão por competências, maior complexidade da atividade tende a exigir:",options:["Maior autonomia, julgamento e responsabilidade","Menor capacidade decisória","Execução exclusivamente repetitiva","Ausência de articulação"],correct:0,explanation:"Atividades complexas demandam maior autonomia, julgamento, articulação e responsabilidade sobre resultados.",source:"Gestão por competências — ENAP"},
 {axis:"Políticas públicas",topic:"Planejamento do SUS",difficulty:"Fácil",prompt:"O Plano de Saúde é caracterizado como:",options:["Instrumento de planejamento de médio prazo do SUS","Relatório diário de produção","Documento exclusivo de auditoria","Substituto do orçamento anual"],correct:0,explanation:"O Plano de Saúde explicita políticas e compromissos de médio prazo do setor saúde.",source:"Ministério da Saúde — Instrumentos de planejamento"},
 {axis:"Políticas públicas",topic:"Programação Anual de Saúde",difficulty:"Média",prompt:"A Programação Anual de Saúde tem como função principal:",options:["Operacionalizar as intenções do Plano de Saúde no período anual","Substituir o Plano de Saúde","Registrar somente despesas","Definir eleições para conselhos"],correct:0,explanation:"A PAS anualiza ações e metas para executar as intenções previstas no Plano de Saúde.",source:"Ministério da Saúde — Instrumentos de planejamento"},
 {axis:"Políticas públicas",topic:"Relatório Anual de Gestão",difficulty:"Média",prompt:"O Relatório Anual de Gestão apresenta principalmente:",options:["Resultados da execução da PAS e orientações para redirecionamento","Apenas previsão de despesas futuras","Somente dados demográficos","Exclusivamente achados disciplinares"],correct:0,explanation:"O RAG apresenta resultados da execução da PAS e subsidia análise e redirecionamento do planejamento.",source:"Ministério da Saúde — RAG"},
 {axis:"Políticas públicas",topic:"Monitoramento",difficulty:"Fácil",prompt:"Monitoramento diferencia-se de avaliação porque, em regra:",options:["Acompanha continuamente informações da implementação","Ocorre apenas após o encerramento da política","Não utiliza indicadores","É sempre externo"],correct:0,explanation:"Monitoramento acompanha a execução e seus sinais ao longo do tempo; avaliação analisa mérito, efeitos ou resultados.",source:"Glossário de monitoramento e avaliação — MS"},
 {axis:"Políticas públicas",topic:"Indicadores",difficulty:"Média",prompt:"Um indicador útil para gestão deve ser:",options:["Relacionado ao objetivo e passível de interpretação","Escolhido apenas por ser fácil de calcular","Desconectado da decisão","Sempre exclusivamente financeiro"],correct:0,explanation:"Indicadores precisam ser relevantes para o objetivo, interpretáveis e úteis para decisão e acompanhamento.",source:"Glossário de monitoramento e avaliação — MS"},
 {axis:"Políticas públicas",topic:"Eficiência, eficácia e efetividade",difficulty:"Difícil",prompt:"Assinale a associação correta:",options:["Eficiência: relação entre recursos e produtos; eficácia: alcance de objetivos; efetividade: efeitos na realidade","Eficiência: impacto; eficácia: custo; efetividade: atividade","Eficiência e eficácia são sinônimos","Efetividade mede apenas quantidade de insumos"],correct:0,explanation:"A distinção clássica relaciona eficiência aos recursos, eficácia ao alcance dos objetivos e efetividade aos efeitos produzidos na realidade.",source:"Glossário de monitoramento e avaliação — MS"},
 {axis:"Políticas públicas",topic:"Articulação interfederativa",difficulty:"Média",prompt:"A gestão compartilhada do SUS pressupõe:",options:["Coordenação entre União, estados e municípios","Centralização de todas as decisões na União","Atuação isolada de cada ente","Ausência de pactuação"],correct:0,explanation:"O SUS é organizado de forma descentralizada e articulada, com responsabilidades compartilhadas e pactuação.",source:"Gestão do SUS — Ministério da Saúde; Decreto nº 7.508/2011"},
 {axis:"Políticas públicas",topic:"Participação social",difficulty:"Fácil",prompt:"A participação social na gestão do SUS é fortalecida por:",options:["Conselhos e conferências de saúde","Decisões sem publicidade","Exclusão de usuários","Relatórios inacessíveis"],correct:0,explanation:"Conselhos e conferências são instâncias de participação da comunidade na gestão do SUS.",source:"Lei nº 8.142/1990"},
 {axis:"Políticas públicas",topic:"Avaliação",difficulty:"Difícil",prompt:"Uma avaliação de política pública deve começar pela definição clara de:",options:["Problema, objetivos, público-alvo e critérios de análise","Apenas o formato do relatório","Somente a fonte de financiamento","A identidade visual do programa"],correct:0,explanation:"Avaliação exige delimitar problema, objetivos, público, teoria de mudança e critérios ou indicadores de análise.",source:"Glossário de monitoramento e avaliação — MS"},
 {axis:"Auditoria e legislação",topic:"Auditoria do SUS",difficulty:"Média",prompt:"A auditoria no SUS tem como finalidade geral:",options:["Verificar conformidade, desempenho e aplicação dos recursos e serviços","Substituir o planejamento","Punir automaticamente todo gestor","Eliminar controles internos"],correct:0,explanation:"Auditoria produz análise independente e sistemática sobre conformidade, desempenho, recursos e serviços.",source:"DenaSUS — Auditoria do SUS"},
 {axis:"Auditoria e legislação",topic:"Auditoria analítica e operativa",difficulty:"Difícil",prompt:"A auditoria analítica utiliza principalmente:",options:["Exame de informações e documentos para orientar a investigação","Somente inspeção física sem documentos","Apenas entrevistas informais","Exclusivamente opinião do auditor"],correct:0,explanation:"A fase analítica examina dados, documentos e informações para compreender o objeto e orientar o trabalho.",source:"DenaSUS — Auditoria do SUS"},
 {axis:"Auditoria e legislação",topic:"Achados",difficulty:"Média",prompt:"Um achado de auditoria deve ser sustentado por:",options:["Evidências suficientes e apropriadas","Rumores sem documentação","Apenas percepção pessoal","Informação sem origem"],correct:0,explanation:"Achados precisam ser fundamentados por evidências suficientes, pertinentes e confiáveis.",source:"Manual de Auditoria Interna do SUS — DenaSUS"},
 {axis:"Auditoria e legislação",topic:"Relatório",difficulty:"Fácil",prompt:"Um relatório de auditoria de qualidade deve apresentar:",options:["Achados, evidências, conclusões e recomendações de forma clara","Somente críticas genéricas","Apenas o resultado desejado","Dados sem análise"],correct:0,explanation:"O relatório deve comunicar achados e evidências, concluir de modo fundamentado e orientar providências.",source:"DenaSUS — Auditoria do SUS"},
 {axis:"Auditoria e legislação",topic:"Lei nº 14.133/2021",difficulty:"Média",prompt:"Na Lei nº 14.133/2021, o planejamento da contratação é relevante porque:",options:["Define necessidade, solução, riscos e condições para a contratação","Elimina a fiscalização contratual","Dispensa justificativa","Substitui o contrato"],correct:0,explanation:"Planejamento identifica a necessidade, avalia soluções, riscos, custos e condições para uma contratação adequada.",source:"Lei nº 14.133/2021 — Planalto"},
 {axis:"Auditoria e legislação",topic:"Lei nº 14.133/2021",difficulty:"Difícil",prompt:"A fiscalização contratual tem relação direta com:",options:["Acompanhamento da execução e registro de ocorrências","Escolha livre do fornecedor após a contratação","Dispensa de controles","Alteração verbal de obrigações"],correct:0,explanation:"Fiscalização acompanha a execução, registra ocorrências e subsidia providências administrativas.",source:"Lei nº 14.133/2021 — Planalto"},
 {axis:"Auditoria e legislação",topic:"Portarias de Consolidação",difficulty:"Média",prompt:"As Portarias de Consolidação GM/MS nº 1 a 6/2017 devem ser estudadas, para este edital, principalmente por:",options:["Temas e dispositivos relacionados ao conteúdo programático","Ordem alfabética de palavras","Comentários não oficiais","Resumos sem conferência"],correct:0,explanation:"A triagem por temas e dispositivos permite estudar a norma extensa de modo alinhado ao edital e à fonte oficial.",source:"Normas consolidadas — Ministério da Saúde"},
 {axis:"Auditoria e legislação",topic:"Financiamento do SUS",difficulty:"Média",prompt:"A transparência e o controle do financiamento da saúde são fortalecidos por:",options:["Prestação de contas, relatórios e fiscalização","Informação exclusivamente interna","Ausência de indicadores","Dados sem publicidade"],correct:0,explanation:"Prestação de contas, relatórios, transparência e fiscalização sustentam o controle do financiamento.",source:"LC nº 141/2012; Ministério da Saúde"},
 {axis:"Auditoria e legislação",topic:"Contratação direta",difficulty:"Difícil",prompt:"A contratação direta, quando admitida pela legislação, exige:",options:["Enquadramento legal e instrução processual adequada","Ausência de justificativa","Escolha informal sem processo","Dispensa de publicidade em qualquer caso"],correct:0,explanation:"Contratação direta não significa contratação sem processo: exige hipótese legal, justificativas e instrução adequada.",source:"Lei nº 14.133/2021 — Planalto"},
 {axis:"Auditoria e legislação",topic:"Controle",difficulty:"Fácil",prompt:"O controle da administração pública deve ser compreendido como:",options:["Conjunto de mecanismos preventivos, concomitantes e posteriores","Atividade exclusivamente punitiva","Ação apenas externa","Procedimento sem relação com resultados"],correct:0,explanation:"Controle pode ocorrer antes, durante e depois da ação, abrangendo conformidade, riscos, desempenho e resultados.",source:"Lei nº 14.133/2021; conteúdo programático do edital"},
 {axis:"Auditoria e legislação",topic:"Auditoria operativa",difficulty:"Difícil",prompt:"A auditoria operativa tende a verificar:",options:["A execução concreta de ações, serviços e processos no campo","Somente o texto da norma","Apenas indicadores financeiros","Exclusivamente entrevistas"],correct:0,explanation:"A auditoria operativa examina a execução e o funcionamento do objeto, confrontando prática, documentos e critérios.",source:"DenaSUS — Auditoria do SUS"},
 {axis:"Auditoria e legislação",topic:"Portaria nº 2/2017",difficulty:"Média",prompt:"Para estudar políticas nacionais de saúde no conjunto das normas consolidadas, a referência mais diretamente associada é:",options:["Portaria de Consolidação GM/MS nº 2/2017","Portaria municipal isolada","Lei nº 14.133/2021","Regimento interno de um hospital"],correct:0,explanation:"A Portaria de Consolidação nº 2 reúne políticas nacionais de saúde, devendo ser consultada no texto oficial vigente.",source:"Portaria de Consolidação GM/MS nº 2/2017"},
 {axis:"Auditoria e legislação",topic:"Evidências",difficulty:"Média",prompt:"Na auditoria, a triangulação de evidências significa:",options:["Confrontar diferentes fontes e técnicas para aumentar a confiabilidade","Usar apenas uma fonte","Ignorar documentos divergentes","Substituir evidência por opinião"],correct:0,explanation:"Confrontar documentos, dados, entrevistas e observação pode aumentar a robustez da conclusão.",source:"Manual de Auditoria Interna do SUS — DenaSUS"},
 {axis:"Gestão pública",topic:"Eficiência e valor público",difficulty:"Difícil",prompt:"Uma decisão eficiente na gestão pública não deve ser avaliada isoladamente pelo custo, mas também por:",options:["Qualidade, alcance do objetivo e valor entregue ao cidadão","Quantidade de reuniões realizadas","Número de normas editadas","Tempo de permanência do gestor"],correct:0,explanation:"Eficiência precisa ser analisada junto a eficácia, qualidade, equidade e valor público produzido.",source:"Conteúdo programático do edital"},
 {axis:"Gestão pública",topic:"Cliente na gestão pública",difficulty:"Média",prompt:"O paradigma do cliente na gestão pública deve ser interpretado com cuidado porque:",options:["Cidadão possui direitos e participa da esfera pública, não sendo apenas consumidor","Serviço público é sempre uma compra privada","Direitos podem ser substituídos por satisfação imediata","Usuário não precisa de transparência"],correct:0,explanation:"O cidadão é titular de direitos e participante da vida pública; a lógica de serviço não pode reduzir tudo a consumo.",source:"Conteúdo programático do edital"},
 {axis:"Gestão pública",topic:"TIC e organizações",difficulty:"Média",prompt:"A adoção de TIC em organizações públicas pode alterar:",options:["Fluxos, papéis, integração e formas de prestação de serviços","Apenas o layout dos documentos","Somente a remuneração","Nada além do arquivo físico"],correct:0,explanation:"Tecnologia modifica processos, fluxos de informação, papéis, integração e canais de entrega.",source:"Conteúdo programático do edital"},
 {axis:"Gestão pública",topic:"Reengenharia",difficulty:"Difícil",prompt:"Reengenharia de processos caracteriza-se por:",options:["Repensar processos de forma ampla para obter melhoria significativa","Apenas trocar o nome das etapas","Manter todos os fluxos sem análise","Focar exclusivamente em aparência"],correct:0,explanation:"Reengenharia propõe repensar processos de forma radical ou ampla, buscando ganhos relevantes de desempenho.",source:"Conteúdo programático do edital"},
 {axis:"Políticas públicas",topic:"RQPC",difficulty:"Média",prompt:"O relatório quadrimestral de prestação de contas está relacionado a:",options:["Acompanhamento periódico da execução e prestação de contas da saúde","Substituição do Plano de Saúde","Registro apenas de pessoal","Auditoria criminal automática"],correct:0,explanation:"O acompanhamento quadrimestral permite prestar contas e monitorar execução, metas e recursos ao longo do ano.",source:"Ministério da Saúde — Instrumentos de planejamento"},
 {axis:"Políticas públicas",topic:"Equidade",difficulty:"Difícil",prompt:"Uma avaliação de política de saúde orientada pela equidade deve considerar:",options:["Como resultados e acesso se distribuem entre diferentes grupos e territórios","Somente a média estadual","Apenas o gasto total","Exclusivamente o número de unidades"],correct:0,explanation:"Equidade exige observar distribuição de acesso, resultados e necessidades entre grupos e territórios.",source:"Gestão do SUS — Ministério da Saúde"},
];

const questionById = new Map(blueprints.map((q, index) => [index + 1, { id: index + 1, ...q }]));

const initialStore = () => {
  try { return JSON.parse(localStorage.getItem("ses-to-simulado") || "null"); } catch { return null; }
};

export default function Home(){
  const saved = useMemo(initialStore, []);
  const { user, loading: authLoading, isAuthenticated, logout } = useAuth();
  const progressQuery = trpc.progress.get.useQuery(undefined, { enabled: isAuthenticated, retry: false });
  const saveProgress = trpc.progress.save.useMutation();
  const [questionOrder,setQuestionOrder] = useState<number[]>(() => {
    return resolveQuestionOrder(saved?.questionOrder, Object.keys(saved?.answers || {}).length > 0, blueprints.length);
  });
  const questions = useMemo(() => questionOrder.map(id => questionById.get(id)!).filter(Boolean), [questionOrder]);
  const [view,setView] = useState<"dashboard"|"simulado"|"desempenho"|"erros"|"fontes">(saved?.view || "dashboard");
  const [current,setCurrent] = useState<number>(saved?.current || 0);
  const [answers,setAnswers] = useState<Record<number,Answer>>(saved?.answers || {});
  const [started,setStarted] = useState<boolean>(saved?.started || false);
  const [showFeedback,setShowFeedback] = useState<boolean>(saved?.showFeedback || false);
  const [selected,setSelected] = useState<number|null>(saved?.selected ?? null);
  const [startTime,setStartTime] = useState<number>(saved?.startTime || Date.now());
  const [elapsed,setElapsed] = useState(0);
  const [localChangedAt,setLocalChangedAt] = useState<number>(saved?.localChangedAt || Date.now());
  const [cloudLoaded,setCloudLoaded] = useState(false);
  const [syncStatus,setSyncStatus] = useState<"local"|"loading"|"synced"|"error">("local");
  const [command,setCommand] = useState("");
  const snapshot = useMemo(() => ({view,current,answers,started,showFeedback,selected,startTime,localChangedAt,questionOrder}), [view,current,answers,started,showFeedback,selected,startTime,localChangedAt,questionOrder]);

  useEffect(()=>{ localStorage.setItem("ses-to-simulado",JSON.stringify(snapshot)); },[snapshot]);
  useEffect(()=>{
    if (!isAuthenticated || progressQuery.isLoading || cloudLoaded) return;
    setSyncStatus("loading");
    if (progressQuery.isError) {
      setSyncStatus("error");
      setCloudLoaded(true);
      toast.error("Não foi possível carregar o progresso em nuvem", { description: "Seu progresso local foi preservado e não será sobrescrito." });
      return;
    }
    if (progressQuery.data?.payload) {
      try {
        const remote = JSON.parse(progressQuery.data.payload);
        const remoteUpdatedAt = progressQuery.data.updatedAt ? new Date(progressQuery.data.updatedAt).getTime() : 0;
        const localIsNewer = shouldPreferLocalProgress(Number(snapshot.localChangedAt || 0), remoteUpdatedAt, Object.keys(snapshot.answers).length > 0);
        if (localIsNewer) {
          saveProgress.mutate({ payload: JSON.stringify(snapshot) }, { onSuccess: () => setSyncStatus("synced"), onError: () => setSyncStatus("error") });
          setSyncStatus("synced");
          toast.success("Progresso local mantido", { description: "A versão mais recente deste dispositivo foi sincronizada." });
        } else if (remote && typeof remote === "object") {
          if (remote.view) setView(remote.view);
          if (typeof remote.current === "number") setCurrent(remote.current);
          if (remote.answers) setAnswers(remote.answers);
          if (typeof remote.started === "boolean") setStarted(remote.started);
          if (typeof remote.showFeedback === "boolean") setShowFeedback(remote.showFeedback);
          if (typeof remote.selected === "number" || remote.selected === null) setSelected(remote.selected);
          if (typeof remote.startTime === "number") setStartTime(remote.startTime);
          if (typeof remote.localChangedAt === "number") setLocalChangedAt(remote.localChangedAt);
          if (isValidQuestionOrder(remote.questionOrder, blueprints.length)) setQuestionOrder(remote.questionOrder);
          setSyncStatus("synced");
          toast.success("Progresso sincronizado", { description: "Seu estudo em nuvem foi carregado nesta sessão." });
        }
      } catch { setSyncStatus("error"); toast.error("Não foi possível ler o progresso salvo na nuvem."); }
    } else {
      saveProgress.mutate({ payload: JSON.stringify(snapshot) }, {
        onSuccess: () => setSyncStatus("synced"),
        onError: () => { setSyncStatus("error"); toast.error("Falha ao criar seu progresso em nuvem", { description: "O progresso local foi preservado." }); },
      });
    }
    setCloudLoaded(true);
  }, [isAuthenticated, progressQuery.isLoading, progressQuery.data, progressQuery.isError, cloudLoaded]);
  useEffect(()=>{
    if (!isAuthenticated || !cloudLoaded || syncStatus === "error") return;
    const timer = window.setTimeout(() => {
      saveProgress.mutate({ payload: JSON.stringify(snapshot) }, {
        onSuccess: () => setSyncStatus("synced"),
        onError: () => { setSyncStatus("error"); toast.error("Falha ao salvar na nuvem", { description: "O progresso continua disponível localmente." }); },
      });
    }, 450);
    return () => window.clearTimeout(timer);
  }, [snapshot, isAuthenticated, cloudLoaded, syncStatus]);
  useEffect(()=>{ const t=setInterval(()=>setElapsed(Math.floor((Date.now()-startTime)/1000)),1000); return ()=>clearInterval(t); },[startTime]);

  const answered = Object.keys(answers).length;
  const correct = Object.values(answers).filter(a=>a.correct).length;
  const score = answered ? Math.round(correct/answered*100) : 0;
  const q = questions[current];
  const axisStats = (Object.keys(axisMeta) as Axis[]).map(axis=>{const list=Object.values(answers).filter(a=>a.axis===axis);return {name:axisMeta[axis].short,axis,acertos:list.filter(a=>a.correct).length,respondidas:list.length,percent:list.length?Math.round(list.filter(a=>a.correct).length/list.length*100):0,color:axisMeta[axis].color};});
  const topicErrors = Object.entries(answers).filter(([,a])=>!a.correct).reduce<Record<string,number>>((acc,[,a])=>{acc[a.topic]=(acc[a.topic]||0)+1;return acc;},{});
  const errorList = Object.entries(topicErrors).sort((a,b)=>b[1]-a[1]);
  const pie = [{name:"Acertos",value:correct,color:"#54B99A"},{name:"Erros",value:answered-correct,color:"#D56B62"},{name:"Pendentes",value:50-answered,color:"#DCE8E5"}];
  const formatTime=(s:number)=>`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;

  function begin(){setStarted(true);setView("simulado");setStartTime(Date.now());setLocalChangedAt(Date.now());toast.success("Simulado iniciado",{description:"Responda uma questão por vez. O progresso é salvo automaticamente."});}
  function choose(i:number){if(showFeedback)return;setSelected(i);setLocalChangedAt(Date.now());}
  function submit(){if(selected===null)return;const isCorrect=selected===q.correct;setAnswers(prev=>({...prev,[q.id]:{selected,correct:isCorrect,axis:q.axis,topic:q.topic,difficulty:q.difficulty}}));setShowFeedback(true);setLocalChangedAt(Date.now());toast(isCorrect?"Resposta correta":"Resposta registrada",{description:isCorrect?"Excelente. Continue nesse ritmo.":"O erro foi salvo no seu caderno de revisão."});}
  function next(){setShowFeedback(false);setSelected(null);setCurrent(Math.min(questions.length-1,current+1));setLocalChangedAt(Date.now());}
  function previous(){setShowFeedback(false);setSelected(null);setCurrent(Math.max(0,current-1));setLocalChangedAt(Date.now());}
  function reset(){localStorage.removeItem("ses-to-simulado");setQuestionOrder(createQuestionOrder(blueprints.length));setAnswers({});setCurrent(0);setStarted(false);setShowFeedback(false);setSelected(null);setView("dashboard");setStartTime(Date.now());setLocalChangedAt(Date.now());toast.success("Progresso reiniciado",{description:"Uma nova ordem de questões foi criada."});}
  function go(v:typeof view){setView(v); if(v==="simulado"&&!started)begin();}
  function runCommand(raw:string){
    const value = raw.trim().toUpperCase();
    if (!value) return;
    if (value === "PAINEL" || value === "DASHBOARD") go("dashboard");
    else if (value === "REVISÃO" || value === "REVISAO" || value === "REFAZER") go(value === "REFAZER" ? "erros" : "desempenho");
    else if (value === "SIMULADO" || value === "CONTINUAR") go("simulado");
    else if (value === "FONTES") go("fontes");
    else if (value === "FINALIZAR") go("desempenho");
    else if (value === "PAUSA") toast("Sessão pausada",{description:"Seu progresso continua salvo. Retome quando quiser."});
    else toast.info("Comando não reconhecido",{description:"Use PAINEL, REVISÃO, REFAZER, SIMULADO ou FONTES."});
    setCommand("");
  }

  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><img src="/manus-storage/simulado-mark_3b0fb8a2.png" alt=""/><div><span>SIMULADO</span><strong>GESTOR EM SAÚDE</strong></div></div>
      <div className="exam-tag">SES-TO · 2026</div>
      <nav className="nav">{[["dashboard","Visão geral",LayoutDashboard],["simulado","Simulado",ListChecks],["desempenho","Desempenho",BarChart3],["erros","Caderno de erros",BookOpenCheck],["fontes","Fontes de estudo",FileText]].map(([id,label,Icon])=><button key={id as string} className={view===id?"active":""} onClick={()=>go(id as typeof view)}><Icon size={18}/><span>{label as string}</span>{id==="erros"&&errorList.length>0&&<b>{errorList.length}</b>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="mini-progress"><span>Progresso geral</span><strong>{answered}/50</strong><Progress value={answered/50*100}/></div><button className="reset-link" onClick={reset}><RotateCcw size={15}/> Reiniciar progresso</button></div>
    </aside>
    <main className="main-area">
      <header className="topbar"><div className="topbar-title"><div className="topbar-mark"><img src="/manus-storage/simulado-mark_3b0fb8a2.png" alt=""/></div><div><span className="eyebrow">PAINEL DE PREPARAÇÃO</span><h1>{view==="dashboard"?"Seu próximo ganho está nos erros recorrentes.":view==="simulado"?"Simulado específico · Questões FGV":view==="desempenho"?"Desempenho por eixo do edital":view==="erros"?"Caderno de erros": "Fontes que sustentam o estudo"}</h1></div></div><div className="top-actions"><div className="time-chip"><Clock3 size={16}/><span>{formatTime(elapsed)}</span></div>{authLoading?<Loader2 size={17} className="spin"/>:isAuthenticated?<div className="user-chip"><span>{user?.name || user?.email || "Conta conectada"}</span><button onClick={()=>logout()} aria-label="Sair"><LogOut size={14}/></button></div>:<Button variant="outline" onClick={startLogin}><LogIn size={15}/> Entrar para salvar</Button>}{isAuthenticated&&<span className={`sync-indicator ${syncStatus}`} title="Status da sincronização">{syncStatus==="loading"?"Sincronizando…":syncStatus==="error"?"Não sincronizado":"Sincronizado"}</span>}<Button variant="outline" size="icon" aria-label="Configurações"><Settings2 size={17}/></Button></div></header>
      <div className="reference-command-bar"><span><strong>Comandos:</strong> PAINEL · REVISÃO · REFAZER · SIMULADO · PAUSA · CONTINUAR · FONTES · FINALIZAR</span><form onSubmit={(event)=>{event.preventDefault();runCommand(command);}}><input value={command} onChange={(event)=>setCommand(event.target.value)} placeholder="Digite um comando" aria-label="Digite um comando"/><button type="submit">Executar</button></form></div>
      {view==="dashboard"&&<Dashboard answered={answered} correct={correct} score={score} axisStats={axisStats} pie={pie} begin={begin} go={go} errorList={errorList}/>} 
      {view==="simulado"&&<Quiz questions={questions} q={q} current={current} answers={answers} selected={selected} showFeedback={showFeedback} choose={choose} submit={submit} next={next} previous={previous} score={score} answered={answered} goTo={(index)=>{setCurrent(index);setShowFeedback(Boolean(answers[questions[index].id]));setSelected(answers[questions[index].id]?.selected ?? null);}}/>} 
      {view==="desempenho"&&<Performance axisStats={axisStats} answered={answered} correct={correct} score={score} pie={pie}/>} 
      {view==="erros"&&<Errors errorList={errorList} answers={answers} questions={questions}/>} 
      {view==="fontes"&&<Sources/>}
    </main>
  </div>
}

function Dashboard({answered,correct,score,axisStats,pie,begin,go,errorList}:{answered:number;correct:number;score:number;axisStats:any[];pie:any[];begin:()=>void;go:(v:any)=>void;errorList:any[]}){
 return <div className="content"><section className="hero-panel"><div><span className="section-kicker">PLANO DE 50 QUESTÕES</span><h2>Resolver. Corrigir.<br/><em>Revisar com método.</em></h2><p>Uma bateria específica de Gestor em Saúde, dividida em quatro eixos do edital e acompanhada por métricas que mostram o que estudar depois.</p><div className="hero-actions"><Button onClick={begin} className="primary-btn"><Target size={17}/> {answered?`Retomar da questão ${String(Math.min(answered+1,50)).padStart(2,"0")}`:"Resolver questão 01"}</Button><button className="text-btn" onClick={()=>go("fontes")}>Ver fontes oficiais <ChevronRight size={16}/></button></div></div><div className="hero-art"><img src="/manus-storage/health-study-illustration_cbeefe79.png" alt="Ilustração editorial de estudo em saúde"/></div></section>
 <section className="stat-grid"><div className="stat-card"><div className="stat-icon teal"><Gauge size={18}/></div><span>Aproveitamento</span><strong>{score}%</strong><small>{correct} acertos de {answered||0} respondidas</small></div><div className="stat-card"><div className="stat-icon blue"><ListChecks size={18}/></div><span>Progresso</span><strong>{answered}<small>/50</small></strong><small>questões concluídas</small></div><div className="stat-card"><div className="stat-icon coral"><BookOpenCheck size={18}/></div><span>Para revisar</span><strong>{errorList.length}</strong><small>tópicos no caderno de erros</small></div><div className="stat-card accent-card"><div className="mini-brand-mark"><img src="/manus-storage/simulado-mark_3b0fb8a2.png" alt=""/></div><span>Meta de segurança</span><strong>80%</strong><div className="tiny-line"><i style={{width:`${Math.min(score/80*100,100)}%`}}></i></div><small>{score>=80?"Meta atingida":"Continue acumulando consistência"}</small></div></section>
 <section className="dashboard-grid"><div className="panel axis-panel"><div className="panel-head"><div><span className="section-kicker">MAPA DO EDITAL</span><h3>Desempenho por eixo</h3></div><button onClick={()=>go("desempenho")} className="link-btn">Abrir relatório <ChevronRight size={15}/></button></div>{axisStats.map(a=><div className="axis-row" key={a.axis}><div className="axis-label"><span className="axis-dot" style={{background:a.color}}></span><span>{a.axis}</span><b>{a.respondidas?`${a.percent}%`:"—"}</b></div><div className="axis-track"><span style={{width:`${a.respondidas?a.percent:0}%`,background:a.color}}></span></div><small>{a.respondidas}/{a.axis==="Gestão pública"?18:a.axis==="Pessoas e redes"?12:a.axis==="Políticas públicas"?8:12} questões</small></div>)}</div><div className="panel pie-panel"><div className="panel-head"><div><span className="section-kicker">VISÃO RÁPIDA</span><h3>Placar atual</h3></div><Sparkles size={18} color="#54B99A"/></div><div className="pie-wrap"><ResponsiveContainer width="52%" height={170}><PieChart><Pie data={pie} dataKey="value" innerRadius={53} outerRadius={75} paddingAngle={3} stroke="none">{pie.map(p=><Cell key={p.name} fill={p.color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div className="pie-center"><strong>{score}%</strong><span>aproveitamento</span></div></div><div className="legend">{pie.map(p=><div key={p.name}><i style={{background:p.color}}></i><span>{p.name}</span><b>{p.value}</b></div>)}</div></div></section>
 <section className="study-line"><div className="line-head"><div><span className="section-kicker">RITMO DE PREPARAÇÃO</span><h3>Da primeira questão à reta final</h3></div><span className="line-note"><Flag size={13}/> 3 de 4 fases acompanhadas</span></div><div className="line"><div className="line-fill" style={{width:`${Math.min(answered/50*100,100)}%`}}></div>{["Diagnóstico","Cobertura","Consolidação","Reta final"].map((x,i)=><div className={`line-step ${answered>=([0,12,32,50][i])?"done":""}`} key={x}><span>{i+1}</span><small>{x}</small></div>)}</div></section>
 </div>
}

function Quiz({questions,q,current,answers,selected,showFeedback,choose,submit,next,previous,score,answered,goTo}:{questions:Question[];q:Question;current:number;answers:Record<number,Answer>;selected:number|null;showFeedback:boolean;choose:(i:number)=>void;submit:()=>void;next:()=>void;previous:()=>void;score:number;answered:number;goTo:(index:number)=>void}){
 const existing=answers[q.id]; const picked=selected!==null?selected:existing?.selected??null;
 return <div className="quiz-layout"><section className="quiz-main"><div className="question-meta"><div><span className="question-number">QUESTÃO {String(q.id).padStart(2,"0")}</span><Badge className="axis-badge">{q.axis}</Badge><Badge variant="outline">{q.difficulty}</Badge></div><span className="question-topic">{q.topic}</span></div><div className="question-card"><div className="prompt">{q.prompt}</div><div className="options">{q.options.map((op,i)=><button key={op} className={`option ${picked===i?"selected":""} ${showFeedback&&i===q.correct?"correct":""} ${showFeedback&&picked===i&&i!==q.correct?"wrong":""}`} onClick={()=>choose(i)}><span className="option-letter">{String.fromCharCode(65+i)}</span><span>{op}</span>{showFeedback&&i===q.correct&&<CheckCircle2 className="option-state" size={19}/>} {showFeedback&&picked===i&&i!==q.correct&&<XCircle className="option-state" size={19}/>}</button>)}</div><div className="question-footer"><span><CircleHelp size={16}/> Escolha uma alternativa para continuar</span><span>{q.source}</span></div></div>{showFeedback&&<div className={`feedback ${picked===q.correct?"good":"bad"}`}><div className="feedback-title">{picked===q.correct?<><CheckCircle2 size={20}/> Resposta correta</>:<><XCircle size={20}/> Resposta registrada para revisão</>}</div><p>{q.explanation}</p><div className="feedback-source"><FileText size={15}/> Base: {q.source}</div></div>}<div className="quiz-actions"><Button variant="outline" onClick={previous} disabled={current===0}><ChevronLeft size={16}/> Anterior</Button>{!showFeedback?<Button onClick={submit} disabled={selected===null} className="primary-btn">Confirmar resposta <ChevronRight size={16}/></Button>:<Button onClick={next} className="primary-btn">{current===49?"Ver resultado":"Próxima questão"} <ChevronRight size={16}/></Button>}</div></section><aside className="quiz-rail"><div className="rail-summary"><span className="section-kicker">PROGRESSO</span><strong>{answered}<small>/50</small></strong><Progress value={answered/50*100}/><div className="rail-score"><span>Aproveitamento</span><b>{score}%</b></div></div><div className="rail-questions"><div className="rail-title"><span>Mapa de questões</span><span>{current+1}/50</span></div><div className="question-grid">{questions.map((item,i)=>{const a=answers[item.id];return <button key={item.id} onClick={()=>goTo(i)} className={`${i===current?"current":""} ${a?.correct?"answered-correct":""} ${a&&!a.correct?"answered-wrong":""}`} title={`Questão ${item.id}`}>{item.id}</button>})}</div></div><div className="rail-tip"><Brain size={17}/><span><b>Nota de campo</b> Corrija o raciocínio, não apenas a letra.</span></div></aside></div>
}

function Performance({axisStats,answered,correct,score,pie}:{axisStats:any[];answered:number;correct:number;score:number;pie:any[]}){return <div className="content"><div className="performance-head"><div><span className="section-kicker">ANÁLISE DE DESEMPENHO</span><h2>Seu estudo em números</h2><p>Use os dados para decidir o que revisar na próxima sessão.</p></div><div className="score-display"><span>APROVEITAMENTO</span><strong>{score}%</strong><small>{correct} acertos · {answered} respondidas</small></div></div><div className="chart-grid"><div className="panel chart-panel"><div className="panel-head"><div><span className="section-kicker">POR EIXO</span><h3>Onde está sua força</h3></div></div><ResponsiveContainer width="100%" height={280}><BarChart data={axisStats} layout="vertical" margin={{left:5,right:20}}><CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#DCE8E5"/><XAxis type="number" domain={[0,100]} tickFormatter={v=>`${v}%`} stroke="#8AA0A0"/><YAxis dataKey="name" type="category" width={72} stroke="#5C7575"/><Tooltip formatter={(v)=>[`${v}%`,"Aproveitamento"]}/><Bar dataKey="percent" radius={[0,3,3,0]}>{axisStats.map(a=><Cell key={a.axis} fill={a.color}/>)}</Bar></BarChart></ResponsiveContainer></div><div className="panel chart-panel"><div className="panel-head"><div><span className="section-kicker">COMPOSIÇÃO</span><h3>Placar atual</h3></div></div><div className="big-pie"><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={pie} dataKey="value" innerRadius={72} outerRadius={100} paddingAngle={4} stroke="none">{pie.map(p=><Cell key={p.name} fill={p.color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div><strong>{score}%</strong><span>acertos sobre respondidas</span></div></div></div></div><div className="panel insight-panel"><div className="insight-icon"><Sparkles size={20}/></div><div><span className="section-kicker">LEITURA DO MOMENTO</span><h3>{score>=80?"Você atingiu a meta de segurança.":score>=60?"A base está se formando; agora é hora de fechar lacunas.":"O próximo ganho está em revisar os fundamentos."}</h3><p>O painel é uma bússola, não um julgamento. Compare seu desempenho por eixo e retorne aos tópicos com erros repetidos.</p></div></div></div>}

function Errors({errorList,answers,questions}:{errorList:any[];answers:Record<number,Answer>;questions:Question[]}){const wrong=questions.filter(q=>answers[q.id]&&!answers[q.id].correct);return <div className="content"><div className="performance-head"><div><span className="section-kicker">REVISÃO ATIVA</span><h2>O erro vira próxima ação</h2><p>Esta lista é criada automaticamente quando uma resposta não coincide com o gabarito.</p></div><div className="error-count"><strong>{wrong.length}</strong><span>questões para revisar</span></div></div>{wrong.length===0?<div className="empty-state"><BookOpenCheck size={34}/><h3>Seu caderno ainda está vazio</h3><p>Comece o simulado e cada erro ficará organizado por tópico.</p></div>:<div className="error-layout"><div className="panel error-list">{wrong.map(q=><div className="error-row" key={q.id}><div className="error-q">{String(q.id).padStart(2,"0")}</div><div><div className="error-title">{q.topic}</div><div className="error-meta">{q.axis} · {q.difficulty}</div></div><Badge variant="outline">Revisar</Badge></div>)}</div><div className="panel error-summary"><span className="section-kicker">TÓPICOS RECORRENTES</span><h3>Onde concentrar a próxima sessão</h3>{errorList.slice(0,5).map(([topic,count])=><div className="topic-bar" key={topic}><div><span>{topic}</span><b>{count}</b></div><Progress value={Math.min(count/3*100,100)}/></div>)}</div></div>}</div>}

function Sources(){const sources=[['Edital retificado SES-TO 2026','Prova, pesos, critérios e os 31 tópicos específicos.','FGV','https://conhecimento.fgv.br/sites/default/files/concursos/edital-retificado-ses-to_retificado.pdf'],['Gestão do SUS','Planejamento, gestão compartilhada e instrumentos do SUS.','Ministério da Saúde','https://www.gov.br/saude/pt-br/acesso-a-informacao/gestao-do-sus'],['Auditoria do SUS','Fases, evidências, achados, relatórios e recomendações.','DenaSUS','https://www.gov.br/saude/pt-br/composicao/denasus/sna/publicacoes/auditoria-do-sus-orientacoes-basicas'],['Lei nº 14.133/2021','Licitações, contratos, planejamento e fiscalização.','Planalto','https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2021/lei/l14133.htm'],['Gestão por competências','Competências, desenvolvimento e limites no setor público.','ENAP','https://bibliotecadigital.enap.gov.br/bitstream/1/2522/1/Gcomp%20-%20ApostilaCE.pdf'],['Normas consolidadas do MS','Portarias GM/MS nº 1 a 6/2017 por tema.','Ministério da Saúde','https://www.gov.br/saude/pt-br/acesso-a-informacao/institucional/legislacao/como-consultar/normas-consolidadas']];return <div className="content"><div className="performance-head"><div><span className="section-kicker">BASE DE ESTUDO</span><h2>Fontes que sustentam o treino</h2><p>Use a fonte primária para validar conceitos antes de transformar um erro em anotação.</p></div><Button variant="outline" onClick={()=>toast.info("Fontes organizadas",{description:"Você pode abrir cada referência em uma nova aba."})}><FileText size={16}/> Checklist de fontes</Button></div><div className="source-grid">{sources.map(([title,desc,org,url])=><a className="source-card" href={url} target="_blank" rel="noreferrer" key={title}><div className="source-mark"><FileText size={18}/></div><div><span>{org}</span><h3>{title}</h3><p>{desc}</p><small>abrir fonte <ChevronRight size={14}/></small></div></a>)}</div><div className="source-note"><CircleHelp size={18}/><span>O banco inicial é um protótipo de treinamento. Para uso como material definitivo, valide cada questão e comentário no edital e nas fontes oficiais vigentes.</span></div></div>}
